/**
 * BookingHub — Master forms configuration.
 * This single config drives: SQLite table creation, the generic CRUD API and
 * the generic React master pages (labels, field types, dropdown refs, child tabs).
 *
 * Field: { name, label, type: text|number|date|time|check|select|textarea|option, ref, options, req, ro }
 *  - select + ref  : dropdown loaded from another master table (stores its id)
 *  - option        : dropdown with fixed options
 *  - ro            : read-only (filled by the system)
 */

const f = (name, label, type = 'text', extra = {}) => ({ name, label, type, ...extra });
const sel = (name, label, ref, extra = {}) => ({ name, label, type: 'select', ref, ...extra });
const opt = (name, label, options, extra = {}) => ({ name, label, type: 'option', options, ...extra });
const nameAlias = (nameLabel = 'Name') => [f('name', nameLabel, 'text', { req: 1 }), f('alias', 'Alias')];
const period = () => [f('valid_from', 'Valid From', 'date'), f('valid_to', 'Valid To', 'date')];
const addr = () => [
  f('address1', 'Address 1'), f('street', 'Street'),
  sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'),
  sel('taluka_id', 'Taluka', 'taluka'), f('pin', 'Pin/Zip'),
  sel('region_id', 'Region', 'region'), sel('zone_id', 'Zone', 'zone'),
  f('phone', 'Phone'), f('fax', 'Fax'), f('email', 'Email Id'),
];
const STATUS = ['ACTIVE', 'INACTIVE'];

const MASTERS = [
  /* ============================= AGENCY / CLIENT MASTERS ============================= */
  {
    key: 'agency_type', label: 'Agency Type', group: 'Agency/Client Masters', section: '4.1',
    help: 'Define types of agencies (Accredited, Non-Accredited, Government...) with commission rate and credit days.',
    fields: [
      ...nameAlias('Agency Type Name'),
      sel('ad_category_id', 'Ad Category', 'ad_category'),
      f('effective_from', 'Effective From', 'date'), f('effective_to', 'Effective To', 'date'),
      f('commission_rate', 'Commission Rate %', 'number'),
      opt('commission_on', 'Commission Apply On', ['NET', 'GROSS']),
      f('credit_days', 'Credit Days', 'number'),
    ],
  },
  {
    key: 'agency', label: 'Agency', group: 'Agency/Client Masters', section: '4.2',
    help: 'Stores agents of the company with commission, contacts, bank guarantees and status details.',
    fields: [
      opt('parent_type', 'Type', ['PARENT', 'CHILD']),
      sel('rate_group_id', 'Rate Group', 'rate_group'),
      f('name', 'Agency Name', 'text', { req: 1 }),
      f('sub_agency_code', 'Sub Agency Code'),
      sel('agency_type_id', 'Agency Type', 'agency_type', { req: 1 }),
      f('alias', 'Alias'),
      f('address1', 'Address 1'), f('address2', 'Address 2'), f('address3', 'Address 3'), f('street', 'Street'),
      f('email', 'Email ID'),
      sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'),
      sel('taluka_id', 'Taluka', 'taluka'), f('pin', 'Pin/Zip'),
      sel('region_id', 'Region', 'region'), sel('zone_id', 'Zone', 'zone'),
      f('phone', 'Phone'), f('fax', 'Fax'),
      f('mrv_ref_no', 'MRV Ref. No.'), f('url', 'URL'), f('mrv_region', 'MRV Region'),
      f('credit_days', 'Credit Days', 'number'), f('pan_no', 'PAN No.'),
      f('credit_limit', 'Credit Limits', 'number'), f('tan_no', 'TAN No.'),
      f('no_of_vts', 'No. of VTS', 'number'), f('service_tax_no', 'Service Tax A/C No.'),
      f('business_start_date', 'Business Start Date', 'date'), f('enrollment_date', 'Enrollment Date', 'date'),
      opt('bill_to', 'Bill To', ['PARENT', 'CHILD']),
      sel('representative_id', 'Representative', 'representative'),
      sel('ac_agency_id', 'A/c Agency', 'agency'),
      f('agency_ho', 'Agency HO'), f('sub_agency_ho', 'Sub Agency HO'),
      opt('status', 'Status', STATUS), f('status_date', 'Status Date', 'date'),
      f('status_reason', 'Status Reason'), f('alert', 'Alert', 'textarea'), f('remarks', 'Remarks', 'textarea'),
    ],
    children: [
      { table: 'agency_commission', label: 'Commission Details', fields: [f('effective_from', 'Effective From', 'date'), f('effective_to', 'Effective To', 'date'), f('commission_rate', 'Commission Rate %', 'number'), opt('commission_on', 'Apply On', ['GROSS', 'NET'])] },
      { table: 'agency_paymode', label: 'Pay Mode', fields: [sel('payment_mode_id', 'Payment Mode', 'payment_mode', { req: 1 })] },
      { table: 'agency_contact', label: 'Contact Details', fields: [f('contact_name', 'Contact Person', 'text', { req: 1 }), sel('designation_id', 'Designation', 'designation'), f('phone', 'Phone'), f('mobile', 'Mobile'), f('email', 'Email')] },
      { table: 'agency_bg', label: 'Bank Guarantee', fields: [f('bg_no', 'BG No.', 'text', { req: 1 }), f('amount', 'Amount', 'number'), f('bg_date', 'BG Date', 'date'), f('validity_date', 'Validity Date', 'date'), f('bank', 'Bank')] },
      { table: 'agency_status', label: 'Status Details', fields: [f('valid_from', 'Valid From', 'date'), f('valid_to', 'Valid To', 'date'), sel('status_id', 'Status', 'status_master'), f('circular_no', 'Circular No.'), f('remark', 'Remark')] },
      { table: 'agency_bank', label: 'Bank Master', fields: [sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'), f('bank_no', 'Bank No.'), f('account_no', 'Account No.'), f('bank_name', 'Bank Name'), f('branch_name', 'Branch')] },
    ],
  },
  {
    key: 'ro_book_issue', label: 'RO Book Issue Entry', group: 'Agency/Client Masters', section: '4.3',
    fields: [
      sel('agency_id', 'Agency Name', 'agency', { req: 1 }),
      f('issue_date', 'Issue Date', 'date'), f('issue_no', 'Issue No.'),
      f('from_ro_no', 'From RO No.'), f('till_ro_no', 'Till RO No.'),
      opt('status', 'Status', STATUS),
    ],
  },
  {
    key: 'agency_credit', label: 'Agency Credit Amount', group: 'Agency/Client Masters', section: '4.4',
    fields: [
      sel('company_id', 'Company', 'company'),
      sel('agency_id', 'QBC / Agency Code', 'agency', { req: 1 }),
      f('date', 'Date', 'date'), f('balance', 'Balance', 'number'),
    ],
  },
  {
    key: 'client', label: 'Client', group: 'Agency/Client Masters', section: '4.5',
    help: 'Customers / booking sources with products, brands, executives, contacts and status details.',
    fields: [
      f('name', 'Customer Name', 'text', { req: 1 }), f('alias', 'Alias'),
      sel('rate_group_id', 'Rate Group', 'rate_group'),
      ...addr(),
      f('url', 'URL'), f('no_of_vts', 'No. of VTS', 'number'),
      f('pan_no', 'PAN'), f('service_tax_no', 'Service Tax A/c No.'),
      f('credit_days', 'Credit Days', 'number'), f('credit_limit', 'Credit Limit', 'number'),
      sel('client_category_id', 'Client Category', 'client_category'),
      opt('status', 'Status', STATUS), f('status_date', 'Status Date', 'date'),
      f('status_reason', 'Status Reason'), f('alert', 'Alert', 'textarea'),
    ],
    children: [
      { table: 'client_product', label: 'Product Details', fields: [sel('product_id', 'Product', 'product', { req: 1 }), sel('executive_id', 'Product-Executive', 'executive')] },
      { table: 'client_contact', label: 'Contact Details', fields: [f('contact_name', 'Contact Person', 'text', { req: 1 }), sel('designation_id', 'Designation', 'designation'), f('phone', 'Phone'), f('mobile', 'Mobile'), f('email', 'Email')] },
      { table: 'client_status', label: 'Status Details', fields: [f('from_date', 'From Date', 'date'), f('to_date', 'To Date', 'date'), sel('status_id', 'Status', 'status_master'), f('circular_no', 'Circular No.')] },
      { table: 'client_paymode', label: 'Pay Mode', fields: [sel('payment_mode_id', 'Payment Mode', 'payment_mode', { req: 1 })] },
      { table: 'client_executive', label: 'Executive Details', fields: [sel('executive_id', 'Executive', 'executive', { req: 1 })] },
      { table: 'client_brand', label: 'Brand Details', fields: [sel('product_id', 'Product', 'product', { req: 1 }), sel('brand_id', 'Brand', 'brand'), sel('executive_id', 'Executive', 'executive')] },
    ],
  },
  {
    key: 'agency_category', label: 'Agency Category', group: 'Agency/Client Masters', section: '4.6',
    fields: [sel('agency_type_id', 'Agency Type', 'agency_type'), ...nameAlias('Agency Category Name')],
  },
  { key: 'client_category', label: 'Client Category', group: 'Agency/Client Masters', section: '4.7', fields: nameAlias('Client Category Name') },
  {
    key: 'publisher', label: 'Publisher', group: 'Agency/Client Masters', section: '4.8',
    fields: [
      ...nameAlias('Publisher Name'), f('address1', 'Address'),
      sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'),
      sel('zone_id', 'Zone', 'zone'), sel('region_id', 'Region', 'region'),
      opt('publisher_type', 'Publisher Type', ['SELF', 'OTHER']),
      f('sharing_pct', 'Sharing (%)', 'number'),
    ],
  },
  { key: 'industry', label: 'Industry', group: 'Agency/Client Masters', section: '4.9 / 4.42', fields: nameAlias('Industry Name') },
  { key: 'product', label: 'Product', group: 'Agency/Client Masters', section: '4.10', fields: [sel('industry_id', 'Industry', 'industry'), ...nameAlias('Product Name')] },
  { key: 'brand', label: 'Brand', group: 'Agency/Client Masters', section: '4.11', fields: [sel('product_id', 'Product Category', 'product', { req: 1 }), ...nameAlias('Brand Name')] },
  { key: 'variant', label: 'Variant', group: 'Agency/Client Masters', section: '4.12', fields: [sel('brand_id', 'Brand Name', 'brand', { req: 1 }), ...nameAlias('Variant Name')] },
  { key: 'representative', label: 'Representative', group: 'Agency/Client Masters', section: '4.13', fields: [f('name', 'Representative Name', 'text', { req: 1 })] },

  /* ============================= EXECUTIVE / RETAINER MASTERS ============================= */
  { key: 'designation', label: 'Designation', group: 'Executive/Retainer Masters', section: '4.14', fields: [f('name', 'Name of the Role', 'text', { req: 1 })] },
  {
    key: 'reporting_to', label: 'Reporting To', group: 'Executive/Retainer Masters', section: '4.15',
    fields: [
      f('name', 'Name', 'text', { req: 1 }),
      sel('designation_id', 'Designation', 'designation'),
      opt('level', 'Level', ['1', '2', '3']),
      f('email', 'Email'), f('discount_allowed', 'Discount Allowed %', 'number'),
    ],
  },
  {
    key: 'executive', label: 'Executive', group: 'Executive/Retainer Masters', section: '4.16',
    help: 'Team and personal details of company executives.',
    fields: [
      f('name', 'Executive Name', 'text', { req: 1 }), f('alias', 'Alias'),
      f('team_name', 'Team Name'),
      sel('designation_id', 'Designation', 'designation'),
      sel('reporting_to_id', 'Reporting To', 'reporting_to'),
      sel('zone_id', 'Zone', 'zone'),
      f('email', 'Email'), f('phone', 'Phone'),
      opt('status', 'Status', STATUS),
    ],
    children: [
      { table: 'executive_contact', label: 'Contact Details', fields: [f('address1', 'Address'), f('city', 'City'), f('phone', 'Phone'), f('mobile', 'Mobile'), f('email', 'Email')] },
    ],
  },
  {
    key: 'retainer', label: 'Retainer', group: 'Executive/Retainer Masters', section: '4.17',
    help: 'Retainers work on commission basis like agencies but as individuals.',
    fields: [
      ...nameAlias('Retainer Name'),
      ...addr(),
      f('pan_no', 'PAN'), f('credit_days', 'Credit Days', 'number'),
      opt('status', 'Status', STATUS), f('status_date', 'Status Date', 'date'),
      f('remarks', 'Remarks', 'textarea'),
    ],
    children: [
      { table: 'retainer_status', label: 'Status Detail', fields: [f('from_date', 'From Date', 'date'), f('to_date', 'To Date', 'date'), sel('status_id', 'Status', 'status_master'), f('circular_no', 'Circular No.')] },
      { table: 'retainer_commission', label: 'Commission Details', fields: [f('effective_from', 'Effective From', 'date'), f('effective_to', 'Effective To', 'date'), f('fixed_rate', 'Fixed Commission Rate %', 'number'), f('additional_rate', 'Additional Commission Rate %', 'number'), f('from_amount', 'From Amount', 'number'), f('to_amount', 'To Amount', 'number'), opt('commission_on', 'Apply On', ['GROSS', 'NET'])] },
      { table: 'retainer_paymode', label: 'Payment Mode', fields: [sel('payment_mode_id', 'Payment Mode', 'payment_mode', { req: 1 })] },
      { table: 'retainer_slab', label: 'Commission Slabs', fields: [f('from_days', 'From Days', 'number'), f('till_days', 'Till Days', 'number'), opt('commission_on', 'Commission On', ['GROSS', 'NET']), f('comm_rate', 'Comm. Rate %', 'number')] },
    ],
  },

  /* ============================= ENVIRONMENT MASTERS ============================= */
  {
    key: 'company', label: 'Company', group: 'Environment Masters', section: '4.18',
    fields: [
      ...nameAlias('Company Name'), f('address1', 'Company Address'), f('street', 'Street'),
      sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'), f('pin', 'Pin Code'),
      f('phone1', 'Phone 1'), f('phone2', 'Phone 2'), f('fax', 'Fax'), f('email', 'Email Id'),
      f('st_acc_no', 'ST_Acc_No'), f('pan_no', 'Pan No.'), f('tan_no', 'Tan No.'),
      f('registration_no', 'Registration No.'), f('registration_date', 'Registration Date', 'date'),
      f('remarks', 'Remarks', 'textarea'), f('box', 'Box (PO Box Address)'),
    ],
  },
  {
    key: 'pub_center', label: 'Publication Center', group: 'Environment Masters', section: '4.19',
    fields: [
      opt('printing_center', 'Printing Center', ['YES', 'NO']),
      ...nameAlias('Publication Center Name'), f('address1', 'Address 1'), f('street', 'Street'),
      sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'), f('pin', 'Pin Code'),
      sel('region_id', 'Region', 'region'), sel('zone_id', 'Zone', 'zone'),
      f('fax', 'Fax'), f('phone', 'Phone'), f('email', 'Email Id'),
      opt('status', 'Status', STATUS), f('status_date', 'Status Date', 'date'),
      f('box_address', 'Box Address'), f('remarks', 'Remarks', 'textarea'),
    ],
  },
  {
    key: 'branch', label: 'Branch', group: 'Environment Masters', section: '4.20',
    fields: [
      sel('pub_center_id', 'Publication Center', 'pub_center', { req: 1 }),
      ...nameAlias('Branch Name'), f('address1', 'Address 1'), f('street', 'Street'),
      sel('country_id', 'Country', 'country'), sel('city_id', 'City', 'city'), f('pin', 'Pin Code'),
      sel('region_id', 'Region', 'region'), sel('zone_id', 'Zone', 'zone'),
      f('phone', 'Phone'), f('fax', 'Fax'), f('email', 'Email Id'),
    ],
  },
  { key: 'country', label: 'Country', group: 'Environment Masters', section: '4.21', fields: nameAlias('Country Name') },
  { key: 'state', label: 'State', group: 'Environment Masters', section: '4.22', fields: [sel('country_id', 'Country Name', 'country', { req: 1 }), ...nameAlias('State Name')] },
  { key: 'district', label: 'District', group: 'Environment Masters', section: '4.23', fields: [sel('country_id', 'Country Name', 'country'), sel('state_id', 'State Name', 'state', { req: 1 }), ...nameAlias('District Name')] },
  { key: 'taluka', label: 'Taluka', group: 'Environment Masters', section: '4.24', fields: [sel('district_id', 'District Name', 'district', { req: 1 }), ...nameAlias('Taluka Name')] },
  { key: 'zone', label: 'Zone', group: 'Environment Masters', section: '4.25', fields: nameAlias('Zone Name') },
  { key: 'region', label: 'Region', group: 'Environment Masters', section: '4.26', fields: nameAlias('Region Name') },
  {
    key: 'city', label: 'City', group: 'Environment Masters', section: '4.27',
    fields: [
      ...nameAlias('City Name'),
      sel('country_id', 'Country Name', 'country'), sel('state_id', 'State Name', 'state'),
      sel('district_id', 'District Name', 'district'),
      sel('zone_id', 'Zone Name', 'zone'), sel('region_id', 'Region', 'region'),
      f('std_code', 'City STD Code'), sel('branch_id', 'Branch', 'branch'),
    ],
  },
  { key: 'payment_mode', label: 'Payment Mode', group: 'Environment Masters', section: '4.28', fields: [f('name', 'Payment Mode', 'text', { req: 1 })] },
  { key: 'status_master', label: 'Status', group: 'Environment Masters', section: '4.29', fields: [f('name', 'Status Name', 'text', { req: 1 })] },
  { key: 'ad_type', label: 'Ad Type', group: 'Ad Category', section: '4.30', fields: nameAlias('Ad Type Name') },
  {
    key: 'currency', label: 'Currency', group: 'Environment Masters', section: '4.31',
    fields: [sel('country_id', 'Country Name', 'country'), ...nameAlias('Currency Name')],
    children: [
      { table: 'currency_rate', label: 'Conversion Rate', fields: [f('convert_rate', 'Convert Rate', 'number', { req: 1 }), f('valid_from', 'Valid From', 'date'), f('valid_till', 'Valid Till', 'date')] },
    ],
  },
  { key: 'language', label: 'Language', group: 'Environment Masters', section: '4.32', fields: nameAlias('Language Name') },
  { key: 'bill_status', label: 'Bill Status', group: 'Environment Masters', section: '4.33', fields: nameAlias('Bill Status Description') },
  {
    key: 'user_role', label: 'User Role', group: 'Environment Masters', section: '4.34',
    fields: [...nameAlias('Role Name'), opt('level', 'Level', ['1', '2', '3'])],
  },
  {
    key: 'tax_rate', label: 'Tax Rate', group: 'Environment Masters', section: '4.35',
    fields: [
      f('from_date', 'From Date', 'date'), f('to_date', 'To Date', 'date'),
      f('description', 'Description', 'text', { req: 1 }), f('order_no', 'Order No.', 'number'),
      f('rate', 'Tax Rate %', 'number'), opt('tax_type', 'Type', ['SERVICE TAX', 'VAT', 'GST', 'EDUCATION CESS', 'OTHER']),
    ],
  },
  {
    key: 'ad_category', label: 'Ad Category', group: 'Ad Category', section: '4.36',
    fields: [
      sel('ad_type_id', 'Ad Type', 'ad_type', { req: 1 }),
      ...nameAlias('Ad Category Name'),
      sel('registered_client_id', 'Registered Client', 'client'),
      opt('publish_day', 'Ad Category Day', ['', 'SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY']),
    ],
  },
  { key: 'ad_sub_category', label: 'Ad Sub Category', group: 'Ad Category', section: '4.37', fields: [sel('ad_category_id', 'Ad Category Name', 'ad_category', { req: 1 }), ...nameAlias('Ad Sub Category Name')] },
  { key: 'ad_sub_category3', label: 'Ad Sub Category 3', group: 'Ad Category', section: '4.38', fields: [sel('ad_sub_category_id', 'Ad Sub Category', 'ad_sub_category', { req: 1 }), ...nameAlias('Ad Sub Category 3 Name')] },
  { key: 'ad_sub_category4', label: 'Ad Sub Category 4', group: 'Ad Category', section: '4.39', fields: [sel('ad_sub_category3_id', 'Ad Sub Category 3', 'ad_sub_category3', { req: 1 }), ...nameAlias('Ad Sub Category 4 Name')] },
  { key: 'ad_sub_category5', label: 'Ad Sub Category 5', group: 'Ad Category', section: '4.40', fields: [sel('ad_sub_category4_id', 'Ad Sub Category 4', 'ad_sub_category4', { req: 1 }), ...nameAlias('Ad Sub Category 5 Name')] },
  {
    key: 'category_sequence', label: 'Category Sequence', group: 'Ad Category', section: '4.41',
    fields: [
      opt('day', 'Day', ['SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY']),
      sel('center_id', 'Center', 'pub_center'),
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      sel('ad_category_id', 'Ad Category', 'ad_category'),
      f('sequence_no', 'Sequence', 'number'),
    ],
  },
  {
    key: 'pub_cat_ref', label: 'Pub Cat Ref', group: 'Environment Masters', section: '4.43',
    fields: [
      sel('publication_id', 'Publication', 'publication', { req: 1 }),
      sel('ad_category_id', 'Category', 'ad_category'),
      sel('ad_sub_category_id', 'Sub Category', 'ad_sub_category'),
      f('name', 'Name', 'text', { req: 1 }),
    ],
  },
  {
    key: 'caption_master', label: 'Caption', group: 'Environment Masters', section: '4.44',
    fields: [sel('ad_type_id', 'Ad Type', 'ad_type'), f('name', 'Caption', 'text', { req: 1 })],
  },

  /* ============================= PUBLICATION MASTERS ============================= */
  { key: 'publication_type', label: 'Publication Type', group: 'Publication Masters', section: '4.45', fields: nameAlias('Publication Type Name') },
  {
    key: 'publication', label: 'Publication', group: 'Publication Masters', section: '4.46',
    fields: [
      sel('publication_type_id', 'Publication Type', 'publication_type'),
      ...nameAlias('Publication Name'),
      sel('language_id', 'Language', 'language'),
      f('start_date', 'Start Date', 'date'),
      f('contact_person', 'Contact Person'), f('phone', 'Phone No.'), f('fax', 'Fax No.'), f('email', 'Email Id'),
      sel('periodicity_id', 'Periodicity', 'periodicity'),
      f('priority', 'Priority', 'number'),
      f('gutter_width', 'Gutter Width', 'number'), f('column_width', 'Column Width', 'number'),
      f('ro_acceptance_time', 'RO Acceptance Time', 'time'),
      f('min_columns', 'Min No. Of Column', 'number'),
      f('production_days_before', 'Production (Day) Before', 'number'),
      f('publish_days', 'Publication Days (e.g. MON,TUE,...)'),
    ],
  },
  {
    key: 'edition', label: 'Edition', group: 'Publication Masters', section: '4.47',
    fields: [
      sel('publication_id', 'Publication Name', 'publication', { req: 1 }),
      opt('edition_type', 'Edition Type', ['MAIN', 'SUB']),
      f('name', 'Edition Name', 'text', { req: 1 }), f('alias', 'Alias'),
      sel('country_id', 'Country', 'country'),
      sel('pub_center_id', 'Publication Center', 'pub_center'),
      sel('printing_center_id', 'Printing Center', 'pub_center'),
      sel('periodicity_id', 'Periodicity', 'periodicity'),
      f('priority', 'Priority', 'number'), f('circulation', 'Circulation', 'number'),
      sel('uom_id', 'UOM', 'uom'),
      f('no_of_columns', 'No. of Columns', 'number'),
      f('height', 'Height', 'number'), f('width', 'Width', 'number'),
      f('page_area', 'Page Area', 'number', { ro: 1 }),
      f('gutter_width', 'Gutter Width', 'number'), f('column_width', 'Column Width', 'number'),
      f('ro_time', 'RO Time', 'time'),
      f('production_days_before', 'Production (Day) Before', 'number'),
    ],
  },
  { key: 'supplement_type', label: 'Supplement Type', group: 'Publication Masters', section: '4.48', fields: nameAlias('Supplement Type Name') },
  {
    key: 'supplement', label: 'Supplement', group: 'Publication Masters', section: '4.49',
    fields: [
      sel('publication_id', 'Publication Name', 'publication', { req: 1 }),
      sel('edition_id', 'Edition Name', 'edition', { req: 1 }),
      sel('supplement_type_id', 'Supplement Type', 'supplement_type'),
      f('name', 'Supplement Name', 'text', { req: 1 }), f('alias', 'Alias'),
      sel('periodicity_id', 'Periodicity', 'periodicity'),
      sel('uom_id', 'Volume Unit (UOM)', 'uom'),
      f('no_of_columns', 'No. of Columns', 'number'),
      f('height', 'Height', 'number'), f('width', 'Width', 'number'),
      f('gutter_space', 'Gutter Space', 'number'), f('column_space', 'Column Space', 'number'),
      f('ro_time', 'RO Time', 'time'),
      f('production_days_before', 'Production (Day) Before', 'number'),
      f('publish_days', 'Supplement Days (e.g. SUN,WED)'),
    ],
  },
  {
    key: 'package', label: 'Combination/Package', group: 'Publication Masters', section: '4.50',
    help: 'Create packages / combinations of multiple editions. Select editions in the Edition Details tab.',
    fields: [
      sel('center_id', 'Center', 'pub_center'),
      sel('ad_type_id', 'Ad Type', 'ad_type', { req: 1 }),
      sel('ad_category_id', 'Ad Category', 'ad_category'),
      sel('ad_sub_category_id', 'Ad Sub Category', 'ad_sub_category'),
      opt('option_type', 'Options', ['MAIN EDITION', 'SUPPLEMENTS', 'MAIN & SUPPLEMENT', 'PACKAGES']),
      f('name', 'Package Name', 'text', { req: 1 }), f('alias', 'Alias'),
      f('no_of_editions', 'No. of Editions', 'number', { ro: 1 }),
      f('combination_name', 'Combination Name', 'text', { ro: 1 }),
      f('no_of_inserts', 'No. of Inserts', 'number'),
      opt('status', 'Status', STATUS),
    ],
    children: [
      { table: 'package_edition', label: 'Edition Details', fields: [sel('edition_id', 'Edition', 'edition'), sel('supplement_id', 'Supplement', 'supplement')] },
    ],
  },
  {
    key: 'change_package_status', label: 'Change Package Status', group: 'Publication Masters', section: '4.51', virtual: 'package_status',
    fields: [sel('ad_type_id', 'Ad Type', 'ad_type'), sel('package_id', 'Package', 'package', { req: 1 }), opt('status', 'Status', STATUS)],
  },
  {
    key: 'page_type', label: 'Page Type', group: 'Publication Masters', section: '4.52',
    fields: [sel('publication_id', 'Publication', 'publication'), ...nameAlias('Page Type Name'), f('height', 'Height', 'number'), f('width', 'Width', 'number')],
  },
  { key: 'periodicity', label: 'Periodicity', group: 'Publication Masters', section: '4.53', fields: nameAlias('Periodicity Name') },
  {
    key: 'no_issue', label: 'No Issue', group: 'Publication Masters', section: '4.54',
    fields: [sel('edition_id', 'Edition', 'edition', { req: 1 })],
    children: [
      { table: 'no_issue_date', label: 'No Issue Dates', fields: [sel('no_issue_day_id', 'No Issue Day', 'no_issue_day'), f('date', 'Date', 'date', { req: 1 })] },
    ],
  },
  { key: 'no_issue_day', label: 'No Issue Day', group: 'Publication Masters', section: '4.55', fields: [f('name', 'No Issue Day Name', 'text', { req: 1 })] },
  {
    key: 'uom', label: 'Unit of Measurement', group: 'Publication Masters', section: '4.56',
    fields: [
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      opt('uom_type', 'UOM Type', ['DISPLAY', 'CLASSIFIED', 'WEB']),
      opt('description', 'UOM Description', ['ROL (Run on Line)', 'ROD (Run on Display)', 'ROW (Run on Word)', 'ROC (Run on Character)', 'CD (Classified Display)', 'SQCM', 'CC']),
      opt('logo_type', 'Logo Type', ['NO', 'YES']),
      f('logo_uom', 'Logo UOM'),
      f('name', 'UOM Name', 'text', { req: 1 }), f('alias', 'Alias'),
      f('style_sheet', 'Style Sheet'),
    ],
  },
  {
    key: 'ad_size', label: 'Ad Size', group: 'Publication Masters', section: '4.57',
    fields: [
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      sel('ad_category_id', 'Adv Category', 'ad_category'),
      sel('package_id', 'Package', 'package'),
      f('name', 'Size Description', 'text', { req: 1 }),
      f('height', 'Normal Height', 'number'), f('width', 'Normal Width', 'number'),
      sel('color_id', 'Color', 'color'), sel('uom_id', 'UOM', 'uom'),
      f('remarks', 'Remarks'),
    ],
  },

  /* ============================= RATE MASTERS ============================= */
  {
    key: 'rate_master', label: 'Rate Master', group: 'Rate Masters', section: '4.58',
    help: 'Rate card used to compute the cost of an ad booking. Rates are picked automatically while booking.',
    fields: [
      sel('center_id', 'Center', 'pub_center'),
      sel('rate_code_id', 'Rate Code', 'rate_code'),
      sel('rate_group_id', 'Rate Group', 'rate_group'),
      sel('currency_id', 'Currency', 'currency'),
      sel('ad_type_id', 'Ad Type', 'ad_type', { req: 1 }),
      sel('ad_category_id', 'Ad Category', 'ad_category'),
      sel('ad_sub_category_id', 'Ad Sub Category', 'ad_sub_category'),
      sel('package_id', 'Package / Edition', 'package', { req: 1 }),
      sel('uom_id', 'UOM', 'uom', { req: 1 }),
      f('width', 'Width', 'number'),
      f('size_from', 'Size/Line/Words From', 'number'), f('size_to', 'Size/Line/Words To', 'number'),
      f('valid_from', 'Valid From', 'date', { req: 1 }), f('valid_to', 'Valid To', 'date', { req: 1 }),
      f('from_insert', 'From Insert', 'number'), f('to_insert', 'To Insert', 'number'),
      f('consumption_period', 'Consumption Period (days)', 'number'),
      sel('scheme_id', 'Scheme', 'scheme'),
      sel('premium_id', 'Premium (Page)', 'ad_page_premium'),
      sel('color_id', 'Color', 'color'),
      opt('color_charge_type', 'Color Charge Type', ['PERCENTAGE', 'FIXED']),
      sel('agency_type_id', 'Agency Type', 'agency_type'),
      sel('client_category_id', 'Client Cat', 'client_category'),
      f('floor_amount', 'Floor Amount', 'number'), f('floor_discount', 'Floor Discount %', 'number'),
      f('rate', 'Rate (Week Day)', 'number', { req: 1 }),
      f('min_rate', 'Min Rate/Amount', 'number'),
      f('extra_rate', 'Extra Rate (per extra line/word)', 'number'),
      f('weekend_rate', 'Weekend Day Rate', 'number'),
      f('weekend_min_rate', 'Weekend Min Rate', 'number'),
      f('weekend_extra_rate', 'Weekend Extra Rate', 'number'),
      f('remark', 'Remark', 'textarea'),
      opt('status', 'Status', STATUS),
    ],
  },
  {
    key: 'rate_code', label: 'Rate Code', group: 'Rate Masters', section: '4.59',
    fields: [f('name', 'Rate Code', 'text', { req: 1 }), f('remark', 'Remark'), opt('status', 'Status', STATUS)],
  },
  {
    key: 'import_export_ratio', label: 'Import/Export Ratio', group: 'Rate Masters', section: '4.60',
    fields: [
      sel('ad_type_id', 'Ad Type', 'ad_type'), sel('center_id', 'Center', 'pub_center'),
      f('from_date', 'From Date', 'date'), f('to_date', 'To Date', 'date'),
      sel('package_id', 'Package', 'package'), sel('ad_category_id', 'Ad Category', 'ad_category'),
      sel('rate_code_id', 'Rate Code', 'rate_code'), f('ratio', 'Ratio %', 'number'),
    ],
  },
  {
    key: 'edition_ratio', label: 'Edition Ratio', group: 'Rate Masters', section: '4.61',
    fields: [sel('package_id', 'Package', 'package', { req: 1 }), sel('edition_id', 'Edition', 'edition', { req: 1 }), f('ratio', 'Ratio %', 'number')],
  },
  { key: 'rate_group', label: 'Rate Group', group: 'Rate Masters', section: '4.62', fields: nameAlias('Rate Group Name') },
  {
    key: 'color_rate_group', label: 'Color Rate Group', group: 'Rate Masters', section: '4.63',
    fields: [
      opt('color_rate', 'Color Rate', ['OPEN', 'REFERENCE']),
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      sel('package_id', 'Package Code', 'package'),
      sel('publication_id', 'Publication Name', 'publication'),
      sel('color_id', 'Color Name', 'color'),
      f('premium_pct', 'Package Premium %', 'number'),
      f('from_date', 'From Date', 'date'), f('to_date', 'To Date', 'date'),
    ],
  },
  { key: 'contract_type', label: 'Contract Type', group: 'Rate Masters', section: '4.64', fields: nameAlias('Contract Name') },
  {
    key: 'contract', label: 'Contract', group: 'Rate Masters', section: '4.65',
    help: 'Value / volume agreements with agencies. While booking, contract rate overrides rate master.',
    fields: [
      f('contract_date', 'Contract Date', 'date'),
      f('name', 'Contract Name', 'text', { req: 1 }),
      sel('contract_type_id', 'Contract Type', 'contract_type'),
      f('service_tax', 'Service Tax %', 'number'),
      sel('agency_id', 'Agency Name', 'agency'),
      sel('sub_agency_id', 'Sub Agency Name', 'agency'),
      sel('client_id', 'Client Name', 'client'),
      sel('product_id', 'Product', 'product'),
      f('valid_from', 'Valid From', 'date'), f('valid_to', 'Valid To', 'date'),
      f('total_volume', 'Total Contract Volume', 'number'),
      f('total_value', 'Total Contract Value', 'number'),
      f('team_name', 'Team Name'),
      sel('representative_id', 'Representative Name', 'representative'),
      sel('executive_id', 'Executive', 'executive'),
      sel('retainer_id', 'Retainer', 'retainer'),
      f('close_date', 'Close Date', 'date'),
      sel('payment_type_id', 'Payment Type', 'payment_mode'),
      f('caption', 'Caption'),
      f('deal_on', 'Deal On', 'date'),
      f('client_ref_no', 'Client Ref No.'),
      opt('status', 'Status', ['CONFIRM', 'RESERVATION', 'CLOSED']),
      sel('receipt_currency_id', 'Receipt Currency', 'currency'),
      f('deal_from', 'Deal From'),
      sel('center_id', 'Center', 'pub_center'),
      f('translation_charge', 'Add Translation Charge', 'number'),
      f('remark', 'Remark', 'textarea'),
    ],
    children: [
      { table: 'contract_detail', label: 'Contract Details', fields: [sel('ad_category_id', 'Ad Category', 'ad_category'), sel('package_id', 'Package/Edition', 'package'), sel('color_id', 'Color', 'color'), f('rate', 'Contract Rate', 'number', { req: 1 })] },
    ],
  },
  { key: 'color', label: 'Color', group: 'Rate Masters', section: '4.66', fields: nameAlias('Color Name') },
  {
    key: 'color_type', label: 'Color Type', group: 'Rate Masters', section: '4.67',
    fields: [...nameAlias('Color Type Name'), sel('ad_category_id', 'Category', 'ad_category'), sel('edition_id', 'Edition', 'edition')],
  },
  { key: 'bg_color', label: 'BG (Background) Color', group: 'Rate Masters', section: '4.68', fields: [...nameAlias('BG Color Name'), f('charge', 'Charge', 'number')] },
  {
    key: 'bullet', label: 'Bullet (Eye Catcher)', group: 'Rate Masters', section: '4.69',
    fields: [
      sel('pub_center_id', 'Pub Center', 'pub_center'),
      f('name', 'Bullet Description', 'text', { req: 1 }),
      opt('charge_type', 'Charge Type', ['FIXED', 'PERCENTAGE']),
      f('charges', 'Bullet Charges', 'number'),
      f('valid_from', 'Validity From', 'date'), f('valid_till', 'Validity Till', 'date'),
      f('symbol', 'Symbol'), opt('font', 'Font', ['WINGDINGS', 'WEBDINGS']),
      f('remarks', 'Remarks'),
    ],
  },
  {
    key: 'ad_page_premium', label: 'Ad Page Premium', group: 'Rate Masters', section: '4.70',
    fields: [
      f('name', 'Premium Name', 'text', { req: 1 }),
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      sel('ad_category_id', 'Ad Category', 'ad_category'),
      sel('publication_id', 'Publication', 'publication'),
      sel('color_id', 'Color', 'color'),
      sel('edition_id', 'Edition', 'edition'),
      sel('ad_size_id', 'Ad Size Description', 'ad_size'),
      sel('supplement_id', 'Supplement', 'supplement'),
      f('page_no', 'Page No.', 'number'),
      opt('premium_type', 'Premium', ['PERCENTAGE', 'FIXED']),
      f('premium_value', 'Premium Value', 'number'),
      sel('rate_group_id', 'Rate Group', 'rate_group'),
      f('special_position', 'Special Position'),
      opt('solus', 'Solus / Semi Solus', ['', 'SOLUS', 'SEMI SOLUS']),
      ...period(),
      f('page_heading', 'Page Heading'),
      f('premium_days', 'Premium Applicable For (days)'),
    ],
  },
  {
    key: 'scheme', label: 'Scheme', group: 'Rate Masters', section: '4.71',
    fields: [
      f('name', 'Scheme Name', 'text', { req: 1 }),
      ...period(),
      f('paid_insertions', 'Paid Insertions', 'number'),
      f('free_insertions', 'Free Insertions', 'number'),
      f('description', 'Description', 'textarea'),
    ],
  },
  {
    key: 'box', label: 'Box', group: 'Rate Masters', section: '4.72',
    fields: [
      f('name', 'Box Description', 'text', { req: 1 }), f('alias', 'Alias'),
      f('no_of_dispatches', 'No. of Dispatches', 'number'),
      f('national_charges', 'Box Charges (National)', 'number'),
      f('international_charges', 'Box Charges (International)', 'number'),
      ...period(),
      f('remarks', 'Remarks'),
    ],
  },
  {
    key: 'ad_position_type', label: 'Ad Position Type', group: 'Rate Masters', section: '4.73',
    fields: [
      f('name', 'Position Type', 'text', { req: 1 }), f('alias', 'Alias'),
      opt('premium_type', 'Premium Type', ['FIXED', 'PERCENTAGE']),
      f('premium_value', 'Premium', 'number'),
    ],
  },
  {
    key: 'ad_barter', label: 'Ad Barter', group: 'Rate Masters', section: '4.74',
    fields: [
      sel('center_id', 'Center', 'pub_center'), sel('branch_id', 'Branch Name', 'branch'),
      sel('agency_id', 'Agency', 'agency'), sel('client_id', 'Client', 'client'),
      f('name', 'Barter Description', 'text', { req: 1 }),
      f('barter_amount', 'Barter Amount', 'number'),
      f('start_date', 'Start Date', 'date'),
    ],
  },
  {
    key: 'client_product_master', label: 'Client Product', group: 'Rate Masters', section: '4.75',
    fields: [
      f('product_sub_code', 'Product Sub Code'),
      sel('client_id', 'Client Name', 'client', { req: 1 }),
      f('name', 'Product Name', 'text', { req: 1 }),
    ],
  },
  {
    key: 'translation_charge', label: 'Translation Charge', group: 'Rate Masters', section: '4.76',
    fields: [
      sel('ad_type_id', 'Ad Type', 'ad_type'),
      f('name', 'Charge Name', 'text', { req: 1 }), f('alias', 'Charge Alias'),
      opt('charge_type', 'Charge Type', ['FIXED', 'PERCENTAGE']),
      f('charge_amount', 'Charge Amount', 'number'),
      f('valid_from', 'Valid From Date', 'date'), f('valid_to', 'Valid To Date', 'date'),
      opt('charge_active', 'Charge Active', ['YES', 'NO']),
    ],
  },
  { key: 'fmg_reason', label: 'FMG Reason', group: 'Rate Masters', section: '4.77', fields: [f('name', 'FMG Reason Description', 'text', { req: 1 })] },
  {
    key: 'hold_rate', label: 'Hold Rate', group: 'Rate Masters', section: '4.78',
    fields: [sel('rate_code_id', 'Rate Code', 'rate_code', { req: 1 }), opt('status', 'Status', STATUS)],
  },
];

module.exports = { MASTERS };
